[project]
name = "provident-energy-ha"
version = "0.1.0"
description = "Integration for Provident Energy utility usage data for Home Assistant"
requires-python = ">=3.12"
dependencies = [
    "homeassistant>=2024.12.5",
    "requests>=2.32.3",
]
